### ISSUE TITLE
[internal] [help wanted] migrate linting to use eslint

### ISSUE THREAD

**Issue by efx** [gridstack/gridstack.js#763]
[eslint](https://eslint.org/) has superceded [jscs](http://jscs.info/). Eslint has also become the defacto ES linter. Because of this, it makes sense to rely upon eslint instead of jscs and jshint.

# todo

- [ ] identify equivalent eslint style guide, include as extends dependency
- [ ] add eslint lint command, dependency
- [ ] remove jscs, jshint inline directives
- [ ] other stuff?

**Comment by adumesny** [comment]
fixed now
